import type { NotificationEventTypeDef } from "../types/notification-config.types.js";

/**
 * Single source of truth for notification event types.
 * Synced to Mongo on boot. Adding a type = add entry here + dispatch() call site.
 */
export const NOTIFICATION_EVENT_TYPES: NotificationEventTypeDef[] = [
  {
    key: "lead.created",
    module: "leads",
    label: "New lead",
    description:
      "A new lead was created from website forms, chatbot, ads, import, or manual entry.",
    defaultChannels: ["in_app", "email"],
    critical: false,
    supportedSources: [
      "meta_ads",
      "google_ads",
      "website_form",
      "chatbot",
      "whatsapp",
      "instagram",
      "manual",
      "import",
      "api",
    ],
    supportedFilters: ["sources", "assigned_to_me", "unassigned_only", "min_lead_score"],
    recipientStrategy: "account",
    groupable: false,
    legacyBucket: "new_lead",
  },
  {
    key: "lead.assigned",
    module: "leads",
    label: "Lead assigned",
    description: "A lead was assigned to you or your team.",
    defaultChannels: ["in_app", "email"],
    critical: false,
    supportedSources: [],
    supportedFilters: ["assigned_to_me"],
    recipientStrategy: "assignee",
    groupable: false,
    legacyBucket: "new_lead",
  },
  {
    key: "lead.status_changed",
    module: "leads",
    label: "Lead status changed",
    description: "A lead’s status was updated.",
    defaultChannels: ["in_app"],
    critical: false,
    supportedSources: [],
    supportedFilters: ["assigned_to_me"],
    recipientStrategy: "assignee",
    groupable: false,
  },
  {
    key: "lead.followup_due",
    module: "leads",
    label: "Follow-up due",
    description: "A follow-up on a lead is due soon.",
    defaultChannels: ["in_app", "email"],
    critical: false,
    supportedSources: [],
    supportedFilters: ["assigned_to_me"],
    recipientStrategy: "assignee",
    groupable: true,
  },
  {
    key: "lead.followup_overdue",
    module: "leads",
    label: "Follow-up overdue",
    description: "A follow-up on a lead is overdue.",
    defaultChannels: ["in_app", "email"],
    critical: false,
    supportedSources: [],
    supportedFilters: ["assigned_to_me"],
    recipientStrategy: "assignee",
    groupable: true,
  },
  {
    key: "conversation.message_received",
    module: "conversations",
    label: "New message",
    description: "A customer sent a message on WhatsApp, Instagram, or chat.",
    defaultChannels: ["in_app"],
    critical: false,
    supportedSources: ["whatsapp", "instagram", "chatbot"],
    supportedFilters: ["sources", "assigned_to_me", "unassigned_only"],
    recipientStrategy: "assignee",
    groupable: true,
    legacyBucket: "direct_messages",
  },
  {
    key: "conversation.intervention_requested",
    module: "conversations",
    label: "Human intervention requested",
    description: "Someone requested that you take over a live chat.",
    defaultChannels: ["in_app", "email"],
    critical: false,
    supportedSources: ["whatsapp"],
    supportedFilters: ["assigned_to_me"],
    recipientStrategy: "team",
    groupable: false,
    legacyBucket: "communication",
  },
  {
    key: "conversation.unanswered_sla",
    module: "conversations",
    label: "Unanswered SLA",
    description: "A conversation waited too long without a reply.",
    defaultChannels: ["in_app", "email"],
    critical: false,
    supportedSources: ["whatsapp", "instagram", "chatbot"],
    supportedFilters: ["sources", "assigned_to_me"],
    recipientStrategy: "assignee",
    groupable: true,
  },
  {
    key: "conversation.mentioned",
    module: "conversations",
    label: "Mentioned in conversation",
    description: "You were mentioned in a conversation note or chat.",
    defaultChannels: ["in_app"],
    critical: false,
    supportedSources: [],
    supportedFilters: [],
    recipientStrategy: "assignee",
    groupable: false,
    legacyBucket: "communication",
  },
  {
    key: "chatbot.handoff",
    module: "conversations",
    label: "Chatbot handoff",
    description: "The chatbot handed a conversation to a human agent.",
    defaultChannels: ["in_app"],
    critical: false,
    supportedSources: ["chatbot", "whatsapp"],
    supportedFilters: ["sources", "assigned_to_me", "unassigned_only"],
    recipientStrategy: "team",
    groupable: false,
    legacyBucket: "chatbot",
  },
  {
    key: "email.reply_received",
    module: "email",
    label: "Email reply received",
    description: "A contact replied to an email conversation.",
    defaultChannels: ["in_app", "email"],
    critical: false,
    supportedSources: [],
    supportedFilters: ["assigned_to_me"],
    recipientStrategy: "assignee",
    groupable: true,
    legacyBucket: "communication",
  },
  {
    key: "email.bounced",
    module: "email",
    label: "Email bounced",
    description: "An outbound email bounced.",
    defaultChannels: ["in_app", "email"],
    critical: false,
    supportedSources: [],
    supportedFilters: [],
    recipientStrategy: "owner",
    groupable: true,
    legacyBucket: "communication",
  },
  {
    key: "email.campaign_completed",
    module: "campaigns",
    label: "Campaign completed",
    description: "An email or WhatsApp campaign finished sending.",
    defaultChannels: ["in_app", "email"],
    critical: false,
    supportedSources: [],
    supportedFilters: [],
    recipientStrategy: "owner",
    groupable: false,
    legacyBucket: "communication",
  },
  {
    key: "whatsapp.template_status_changed",
    module: "system",
    label: "WhatsApp template status",
    description: "A WhatsApp template was approved, rejected, or paused.",
    defaultChannels: ["in_app", "email"],
    critical: false,
    supportedSources: ["whatsapp"],
    supportedFilters: [],
    recipientStrategy: "admins",
    groupable: false,
    legacyBucket: "system_alerts",
  },
  {
    key: "whatsapp.quality_changed",
    module: "system",
    label: "WhatsApp quality rating",
    description: "Your WhatsApp number quality rating changed.",
    defaultChannels: ["in_app", "email"],
    critical: false,
    supportedSources: ["whatsapp"],
    supportedFilters: [],
    recipientStrategy: "admins",
    groupable: false,
    legacyBucket: "system_alerts",
  },
  {
    key: "system.integration_error",
    module: "system",
    label: "Integration error",
    description: "An integration failed or needs attention.",
    defaultChannels: ["in_app", "email"],
    critical: false,
    supportedSources: [],
    supportedFilters: [],
    recipientStrategy: "admins",
    groupable: true,
    legacyBucket: "system_alerts",
  },
  {
    key: "system.whatsapp_disconnected",
    module: "system",
    label: "WhatsApp disconnected",
    description: "WhatsApp Business connection was lost.",
    defaultChannels: ["in_app", "email"],
    critical: true,
    supportedSources: ["whatsapp"],
    supportedFilters: [],
    recipientStrategy: "admins",
    groupable: false,
    legacyBucket: "system_alerts",
  },
  {
    key: "system.gmail_token_expired",
    module: "system",
    label: "Gmail connection expired",
    description: "Gmail OAuth token expired and must be reconnected.",
    defaultChannels: ["in_app", "email"],
    critical: true,
    supportedSources: [],
    supportedFilters: [],
    recipientStrategy: "owner",
    groupable: false,
    legacyBucket: "system_alerts",
  },
];

export const NOTIFICATION_EVENT_TYPE_MAP = Object.fromEntries(
  NOTIFICATION_EVENT_TYPES.map((event) => [event.key, event]),
) as Record<string, NotificationEventTypeDef>;

export function getEventType(eventKey: string) {
  return NOTIFICATION_EVENT_TYPE_MAP[eventKey] ?? null;
}

export function getEventTypesByModule() {
  return NOTIFICATION_EVENT_TYPES.reduce<
    Record<string, NotificationEventTypeDef[]>
  >((acc, event) => {
    (acc[event.module] ||= []).push(event);
    return acc;
  }, {});
}
