export const EMAIL_CAMPAIGN_STATUS = {
  DRAFT: "DRAFT",
  SCHEDULED: "SCHEDULED",
  QUEUED: "QUEUED",
  SENDING: "SENDING",
  COMPLETED: "COMPLETED",
  PAUSED: "PAUSED",
  CANCELED: "CANCELED",
  FAILED: "FAILED",
} as const;

export type EmailCampaignStatus =
  (typeof EMAIL_CAMPAIGN_STATUS)[keyof typeof EMAIL_CAMPAIGN_STATUS];

export const EMAIL_RECIPIENT_STATUS = {
  PENDING: "PENDING",
  QUEUED: "QUEUED",
  SENT: "SENT",
  DELIVERED: "DELIVERED",
  BOUNCED: "BOUNCED",
  OPENED: "OPENED",
  CLICKED: "CLICKED",
  UNSUBSCRIBED: "UNSUBSCRIBED",
  FAILED: "FAILED",
  SKIPPED: "SKIPPED",
} as const;

export type EmailRecipientStatus =
  (typeof EMAIL_RECIPIENT_STATUS)[keyof typeof EMAIL_RECIPIENT_STATUS];

export const EMAIL_EVENT_TYPE = {
  SENT: "SENT",
  DELIVERED: "DELIVERED",
  OPENED: "OPENED",
  CLICKED: "CLICKED",
  BOUNCED: "BOUNCED",
  FAILED: "FAILED",
  UNSUBSCRIBED: "UNSUBSCRIBED",
  COMPLAINED: "COMPLAINED",
} as const;

export type EmailEventType =
  (typeof EMAIL_EVENT_TYPE)[keyof typeof EMAIL_EVENT_TYPE];

export const EMAIL_SUPPRESSION_REASON = {
  UNSUBSCRIBED: "UNSUBSCRIBED",
  HARD_BOUNCE: "HARD_BOUNCE",
  SPAM_COMPLAINT: "SPAM_COMPLAINT",
  INVALID_EMAIL: "INVALID_EMAIL",
} as const;

export const EMAIL_TEMPLATE_CATEGORY = {
  PROMOTION: "promotion",
  NEWSLETTER: "newsletter",
  WELCOME: "welcome",
  FOLLOW_UP: "follow-up",
  EVENT: "event",
  OFFER: "offer",
  GENERAL: "general",
} as const;

export const EMAIL_ERROR = {
  EMAIL_MARKETING_NOT_AVAILABLE: "EMAIL_MARKETING_NOT_AVAILABLE",
  EMAIL_LIMIT_REACHED: "EMAIL_LIMIT_REACHED",
  CAMPAIGN_LIMIT_REACHED: "CAMPAIGN_LIMIT_REACHED",
  CAMPAIGN_NOT_FOUND: "CAMPAIGN_NOT_FOUND",
  CAMPAIGN_INVALID: "CAMPAIGN_INVALID",
  CAMPAIGN_ALREADY_SENT: "CAMPAIGN_ALREADY_SENT",
  CAMPAIGN_ALREADY_RUNNING: "CAMPAIGN_ALREADY_RUNNING",
  NO_RECIPIENTS: "NO_RECIPIENTS",
  SENDER_NOT_VERIFIED: "SENDER_NOT_VERIFIED",
  INVALID_EMAIL_CONTENT: "INVALID_EMAIL_CONTENT",
  EMAIL_PROVIDER_ERROR: "EMAIL_PROVIDER_ERROR",
  EMAIL_SEND_FAILED: "EMAIL_SEND_FAILED",
  EMAIL_UNSUBSCRIBED: "EMAIL_UNSUBSCRIBED",
  EMAIL_SUPPRESSED: "EMAIL_SUPPRESSED",
  MISSING_UNSUBSCRIBE: "MISSING_UNSUBSCRIBE",
} as const;

export const EMAIL_CAMPAIGN_BATCH_SIZE = Number(
  process.env.EMAIL_CAMPAIGN_BATCH_SIZE || 50,
);
export const EMAIL_SEND_GAP_MS = Number(process.env.EMAIL_SEND_GAP_MS || 200);

export const ALLOWED_CAMPAIGN_TRANSITIONS: Record<string, string[]> = {
  [EMAIL_CAMPAIGN_STATUS.DRAFT]: [
    EMAIL_CAMPAIGN_STATUS.SCHEDULED,
    EMAIL_CAMPAIGN_STATUS.QUEUED,
    EMAIL_CAMPAIGN_STATUS.CANCELED,
  ],
  [EMAIL_CAMPAIGN_STATUS.SCHEDULED]: [
    EMAIL_CAMPAIGN_STATUS.QUEUED,
    EMAIL_CAMPAIGN_STATUS.CANCELED,
    EMAIL_CAMPAIGN_STATUS.DRAFT,
  ],
  [EMAIL_CAMPAIGN_STATUS.QUEUED]: [
    EMAIL_CAMPAIGN_STATUS.SENDING,
    EMAIL_CAMPAIGN_STATUS.PAUSED,
    EMAIL_CAMPAIGN_STATUS.CANCELED,
    EMAIL_CAMPAIGN_STATUS.FAILED,
  ],
  [EMAIL_CAMPAIGN_STATUS.SENDING]: [
    EMAIL_CAMPAIGN_STATUS.COMPLETED,
    EMAIL_CAMPAIGN_STATUS.PAUSED,
    EMAIL_CAMPAIGN_STATUS.FAILED,
    EMAIL_CAMPAIGN_STATUS.CANCELED,
  ],
  [EMAIL_CAMPAIGN_STATUS.PAUSED]: [
    EMAIL_CAMPAIGN_STATUS.QUEUED,
    EMAIL_CAMPAIGN_STATUS.CANCELED,
  ],
};

export const PERSONALIZATION_FALLBACKS: Record<string, string> = {
  firstName: "there",
  lastName: "",
  email: "",
  companyName: "your team",
  organizationName: "us",
  hotelName: "",
  bookingLink: "",
  leadSource: "",
  assignedUser: "",
};
