export const QUEUE_JOBS = {
  SEND_ONBOARDING_EMAIL: "send-onboarding-email",
  LEAD_ACKNOWLEDGEMENT_EMAIL: "lead-acknowledgement-email",
  SEND_TASK_ASSIGNED_EMAIL: "send-task-assigned-email",
  SEND_LEAD_ASSIGNED_EMAIL: "send-lead-assigned-email",
  LEAD_NOTIFICATION_EMAIL: "lead-notification-email",
  WHATSAPP_ESCALATION_EMAIL: "whatsapp-escalation-email",
  EMAIL_CAMPAIGN_PREPARE: "email-campaign-prepare",
  EMAIL_CAMPAIGN_SEND_BATCH: "email-campaign-send-batch",
  WHATSAPP_CAMPAIGN_PREPARE: "whatsapp-campaign-prepare",
  WHATSAPP_CAMPAIGN_SEND_BATCH: "whatsapp-campaign-send-batch",
  CONTACT_IMPORT_VALIDATE: "import:validate",
  CONTACT_IMPORT_CHUNK: "import:chunk",
  CONTACT_IMPORT_FINALIZE: "import:finalize",
  CONTACT_IMPORT_SWEEP: "import:sweep",
  CONTACT_IMPORT_CLEANUP: "import:cleanup",
};
