export const FEATURE = {
  ACCOUNT_MANAGEMENT: "ACCOUNT_MANAGEMENT",
  CHATBOTS: "CHATBOTS",
  WHATSAPP_MESSAGING: "WHATSAPP_MESSAGING",
  LEAD_MANAGEMENT: "LEAD_MANAGEMENT",
  WEBHOOKS: "WEBHOOKS",
  WHATSAPP_AI_AGENT: "WHATSAPP_AI_AGENT",
} as const;

export type FeatureKey = (typeof FEATURE)[keyof typeof FEATURE];

export const FEATURE_TYPE = {
  BOOLEAN: "BOOLEAN",
  LIMITED: "LIMITED",
  USAGE_BASED: "USAGE_BASED",
  PAID_ADDON: "PAID_ADDON",
} as const;

export const FEATURE_TYPES: Record<FeatureKey, string> = {
  ACCOUNT_MANAGEMENT: FEATURE_TYPE.LIMITED,
  CHATBOTS: FEATURE_TYPE.LIMITED,
  WHATSAPP_MESSAGING: FEATURE_TYPE.USAGE_BASED,
  LEAD_MANAGEMENT: FEATURE_TYPE.USAGE_BASED,
  WEBHOOKS: FEATURE_TYPE.LIMITED,
  WHATSAPP_AI_AGENT: FEATURE_TYPE.PAID_ADDON,
};

export const USAGE_METRIC = {
  TEAM_MEMBERS: "teamMembers",
  ACCOUNTS: "accounts",
  CHATBOTS: "chatbots",
  WEBHOOKS: "webhooks",
  LEADS: "leads",
  WHATSAPP_MESSAGES: "whatsappMessages",
  AI_CONVERSATIONS: "aiConversations",
} as const;

export type UsageMetric = (typeof USAGE_METRIC)[keyof typeof USAGE_METRIC];

export const PLAN_LIMIT = {
  TEAM_MEMBERS: "teamMembers",
  ACCOUNTS: "accounts",
  CHATBOTS: "chatbots",
  WEBHOOKS: "webhooks",
  LEADS_PER_MONTH: "leadsPerMonth",
  WHATSAPP_MESSAGES_PER_MONTH: "whatsappMessagesPerMonth",
  AI_CONVERSATIONS_PER_MONTH: "aiConversationsPerMonth",
} as const;

export const SUBSCRIPTION_STATUS = {
  TRIALING: "trialing",
  ACTIVE: "active",
  PAST_DUE: "past_due",
  CANCELED: "canceled",
  EXPIRED: "expired",
} as const;

export type SubscriptionStatusValue =
  (typeof SUBSCRIPTION_STATUS)[keyof typeof SUBSCRIPTION_STATUS];

export const PLAN_CODE = {
  TRIAL: "trial",
  STARTER: "starter",
  PRO: "pro",
  BUSINESS: "business",
  LEGACY: "legacy",
} as const;

export const ADDON_CODE = {
  WHATSAPP_AI_AGENT: "WHATSAPP_AI_AGENT",
} as const;

export const SUBSCRIPTION_ERROR = {
  SUBSCRIPTION_REQUIRED: "SUBSCRIPTION_REQUIRED",
  SUBSCRIPTION_EXPIRED: "SUBSCRIPTION_EXPIRED",
  SUBSCRIPTION_PAST_DUE: "SUBSCRIPTION_PAST_DUE",
  PLAN_LIMIT_REACHED: "PLAN_LIMIT_REACHED",
  FEATURE_NOT_AVAILABLE: "FEATURE_NOT_AVAILABLE",
  WHATSAPP_AI_AGENT_REQUIRED: "WHATSAPP_AI_AGENT_REQUIRED",
  WHATSAPP_MESSAGE_LIMIT_REACHED: "WHATSAPP_MESSAGE_LIMIT_REACHED",
  AI_USAGE_LIMIT_REACHED: "AI_USAGE_LIMIT_REACHED",
  CHATBOT_LIMIT_REACHED: "CHATBOT_LIMIT_REACHED",
  LEAD_LIMIT_REACHED: "LEAD_LIMIT_REACHED",
  WEBHOOK_LIMIT_REACHED: "WEBHOOK_LIMIT_REACHED",
  TEAM_MEMBER_LIMIT_REACHED: "TEAM_MEMBER_LIMIT_REACHED",
  PAYMENT_REQUIRED: "PAYMENT_REQUIRED",
  PAYMENT_FAILED: "PAYMENT_FAILED",
  INVALID_PAYMENT: "INVALID_PAYMENT",
  SUBSCRIPTION_NOT_FOUND: "SUBSCRIPTION_NOT_FOUND",
} as const;

export const SUBSCRIPTION_EVENT = {
  TRIAL_STARTED: "TRIAL_STARTED",
  TRIAL_7_DAYS_LEFT: "TRIAL_7_DAYS_LEFT",
  TRIAL_3_DAYS_LEFT: "TRIAL_3_DAYS_LEFT",
  TRIAL_1_DAY_LEFT: "TRIAL_1_DAY_LEFT",
  TRIAL_EXPIRED: "TRIAL_EXPIRED",
  PLAN_ACTIVATED: "PLAN_ACTIVATED",
  SUBSCRIPTION_CANCELED: "SUBSCRIPTION_CANCELED",
  PAYMENT_VERIFIED: "PAYMENT_VERIFIED",
} as const;

export const BILLING_ROLES = ["OWNER", "ADMIN"] as const;

export const CORE_FEATURES: FeatureKey[] = [
  FEATURE.ACCOUNT_MANAGEMENT,
  FEATURE.CHATBOTS,
  FEATURE.WHATSAPP_MESSAGING,
  FEATURE.LEAD_MANAGEMENT,
  FEATURE.WEBHOOKS,
  FEATURE.WHATSAPP_AI_AGENT,
];
